typescript: fix error
error TS2343: This syntax requires an imported helper named __spreadArray which does not exist in tslib. Consider upgrading your version of tslib.

https://stackoverflow.com/questions/52801814/this-syntax-requires-an-imported-helper-but-module-tslib-cannot-be-found-wit